### ISSUE TITLE
mount under /blog on dockyard.com

### ISSUE THREAD

**Issue by bcardarella** [dockyard/reefpoints#244]
I'd like to explore mounting reefpoint under `/blog` on `dockyard.com` with proper `301` redirects.

@danmcclain can DNS handle this for us?

**Comment by danmcclain** [comment]
@bcardarella We cannot do this with DNS alone. It would not take much work to put together a NGINX config to generate the proper redirects. The question is how do we want to host this? Do you want to keep the blog on GH pages and the site on a different service? Or would we house them both on our own server? If the later is the case, we can still have 2 separate deploys like we currently do, and the NGINX config will handle the rest.

**Comment by acacheung** [comment]
done!
