### ISSUE TITLE
Post: Building An Ember App With Rails Part 2

### ISSUE THREAD

**Issue by lizzerdrix** [dockyard/reefpoints#301]
After changing the title to "Welcome to Boston Ember," the test is still failing with the following error:

![screen shot 2015-03-10 at 7 49 34 am](https://cloud.githubusercontent.com/assets/4008348/6574341/0d91edee-c6fa-11e4-8001-e6f7815422d6.png)

I am running ember-cli v.0.1.15, if that helps. I noticed two other people in the comments had the same issue.

**Comment by michaeldupuisjr** [comment]
@lizzerdrix Checking this out now...

**Comment by bcardarella** [comment]
This is with the latest ember-cli. We need to update the blog:

```javascript
import Ember from 'ember';
import { module, test } from 'qunit';
```

**Comment by michaeldupuisjr** [comment]
I'm also going to update the post for Rails 4.2.0.

**Comment by lizzerdrix** [comment]
I followed these updates and everything was working fine until I got to the second test on landing-page-test.js. I copied the test exactly but now get the following failure:

![screen shot 2015-03-11 at 6 43 56 pm](https://cloud.githubusercontent.com/assets/4008348/6608644/3d650b98-c81f-11e4-9b5b-b953a4e7c5e4.png)

**Comment by bcardarella** [comment]
@lizzerdrix make sure you are passing `assert` into your test function

**Comment by lizzerdrix** [comment]
Yup, this what I have:

```javascript
test('Should allow navigating back to root from another page', function(assert) {
  visit('/about').then(function() {
    click('a:contains("Home")').then(function(assert) {
      assert.notEqual(find('h3').text(), 'About');
    });
  });
});
```
I also tried passing 'assert' into the second line as well just in case, but got the same error.

**Comment by rwjblue** [comment]
@lizzerdrix - What version of qunit do you have in `bower.json`?

**Comment by lizzerdrix** [comment]
@rwjblue 1.17.1

**Comment by rwjblue** [comment]
And ember-qunit version?

**Comment by lizzerdrix** [comment]
@rwjblue 0.2.8

**Comment by michaeldupuisjr** [comment]
@lizzerdrix I've pushed the project I built as I was updating the post. Feel free to compare against your local branch: https://github.com/michaeldupuisjr/bostonember

**Comment by lizzerdrix** [comment]
@michaeldupuisjr it works! thank you so much! the problem was an 'assert' where there should not have been one (on line 3 of the example I gave from my code earlier).

**Comment by michaeldupuisjr** [comment]
Awesome. Thanks for opening up the issue @lizzerdrix!
