### ISSUE TITLE
Fix image src in old post - UX camp project

### ISSUE THREAD

**Issue by rgbcolor** [dockyard/reefpoints#358]
Please change image source to: http://i.imgur.com/K9TBWR9.jpg

in this post: https://dockyard.com/blog/2014/11/12/bring-to-ux-east

**Comment by danmcclain** [comment]
Make sure to use https links for image

**Comment by rgbcolor** [comment]
please use https://i.imgur.com/K9TBWR9.jpg per Dan's comment. Thanks again!
