### ISSUE TITLE
Code block formatting on iOS

### ISSUE THREAD

**Issue by HeroicEric** [dockyard/reefpoints#374]
![img_1085](https://cloud.githubusercontent.com/assets/602204/9152465/aca99fca-3df7-11e5-9da8-0fd8f9934f31.jpg)

iOS 6 Safari

**Comment by bcardarella** [comment]
yeah we've got this tracked internally, thought we had it fixed. Thanks for the heads up :)

**Comment by acacheung** [comment]
dup
