### ISSUE TITLE
Example on how best to override init

### ISSUE THREAD

**Issue by sohara** [DockYard/reefpoints#439]
I've enjoyed the blog posts a lot. Thanks! One of the tips I've take to heart was not overriding init: https://github.com/dockyard/reefpoints/blob/master/source/posts/2015-10-19-2015-dont-dont-override-init.md

However, after reading your blog post I've often wondered if it's best to call `_super()` at the beginning or end of the function. Your blog post suggests that it's better at the end (or at least that's what dockyard has adopted).

But most other code examples call super as the first expression in the function, and today on slack robert jackson informed that it's really the best way to do it. 

quote:
`_super` should always happen in `init` before using `this` for anything
^^ is actually a requirement in ES6 classes

Anway, just wondering if you'd accept a pr on that part.

**Comment by bcardarella** [comment]
It depends upon the context. If you wanted to condition the arguments that are being passed to the original `init` then you need to call `_super` after your code. If you want to invoke the original behavior then you need to call it before.

**Comment by sohara** [comment]
That makes sense. 

What I find lacking from most discussions (all the ones I've come across) of using the `init()` hook are 1) no clear criteria for when one should or should not return, and 2) the idea that `_super()` should be called prior to any use of `this` - although arguably it doesn't have applicability since Ember classes/factories are not (yet) ES6 classes.

**Comment by rwjblue** [comment]
1. Return value is not used at all.
2. `_super` should definitely be called before using `this` (to ensure the prototype is properly setup before attempting to use it), but @bcardarella is totally correct that you may want to massage the arguments and whatnot first.
