### ISSUE TITLE
More info for "Ember Data: Worryless Model Defaults"

### ISSUE THREAD

**Issue by HeroicEric** [DockYard/reefpoints#461]
Post: https://dockyard.com/blog/2016/02/12/defaults-in-ember

It might be worth mentioning that using a complex object for `defaultValue` is actually deprecated now in order to help people avoid this issue.

Was deprecated here https://github.com/emberjs/data/pull/3855

**Comment by bcardarella** [comment]
@rsocci ^

**Comment by bcardarella** [comment]
@rsocci ping on this

**Comment by rsocci** [comment]
Thanks @bcardarella and @HeroicEric, I missed the first ping but I will update!
