### ISSUE TITLE
posts.json can be compressed

### ISSUE THREAD

**Issue by atonse** [DockYard/reefpoints#481]
Looks like the blog currently stores all the posts in a posts.json (generated by Middleman) – this file can easily be gzipped by the web server, since it's currently 1.8MB.

Using nginx, you can apply gzipping to the `application/json` mime type, and cut that download by probably 80-90% (this is already working for JS/CSS).

Example:
```
gzip            on;
gzip_min_length 1000;
gzip_proxied    expired no-cache no-store private auth;
gzip_types      text/plain application/xml;
```

But your posts.json is being returned as `application/octet-stream` which is why it's not gzipping.

As a side note, your version of nginx is almost 2 years old (1.4.2).

PS: I'm an avid reader of Dockyard's blog and an ember/elixir developer – hoping to meet your team at EmberConf next week!

**Comment by bcardarella** [comment]
Thank you, we already have a fix that is going out on Monday. We're moving away from the payload.
